on:
  pull_request:
    branches: [ master ]
jobs:
    ktlint_job:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Run ktlint
        run: ./gradlew ktlintDebugCheck --continue
    lint_job:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: run lint check
        run: ./gradlew lintDebug
    detekt_job:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: run detekt check
        run: ./gradlew detektDebug
        
    assemble_job:
     needs: [ktlint_job, lint_job, detekt_job]
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Restore Cache
       uses: actions/cache@v2
       with:
         path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
         restore-keys: |
           ${{ runner.os }}-gradle-
     - name: Assemble debug apk
       run: ./gradlew assembleDebug

     - name: Upload APK
       uses: actions/upload-artifact@v2
       with:
         name: apk
         path: app/build/outputs/apk/debug/**.apk
    
