on:
  pull_request:
    types: [closed]
    branches: [ dev ]

jobs:
 issue_closer_job:
  runs-on: ubuntu-latest
  steps:
      - name: Closes issues related to a merged pull request.
        uses: Skyyo/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
